### ISSUE TITLE
"textDocument/publishDiagnostics" does not respect client capabilities.

### ISSUE THREAD

**Issue by hugopl** [elbywan/crystalline#16]
Hi,

`"textDocument/publishDiagnostics"` notifications are being sent even if the client capabilities say not to.

A minor issue since the server can just ignore these notifications... and also because any good client must support diagnostics.

**Comment by elbywan** [comment]
> A minor issue since the server can just ignore these notifications... and also because any good client must support diagnostics.

Yeah it's not a big deal but it's always good to stick to the specs.

Closed with #17.
