### ISSUE TITLE
support crystal 1.2.0

### ISSUE THREAD

**Issue by zhenfeng-zhu** [elbywan/crystalline#29]
my crystal version is 1.2.0

git clone to my local dir, and then i run the command like this.

```
$ env LLVM_CONFIG=/usr/local/opt/llvm/bin/llvm-config crystal build ./src/crystalline.cr  -o ./bin/crystalline --release --no-debug -Dpreview_mt
Showing last frame. Use --error-trace for full trace.

In /usr/local/Cellar/crystal/1.2.0/src/compiler/crystal/tools/doc/generator.cr:1:1

 1 | require "../../../../../lib/markd/src/markd"
     ^
Error: can't find file '../../../../../lib/markd/src/markd' relative to '/usr/local/Cellar/crystal/1.2.0/src/compiler/crystal/tools/doc/generator.cr'

```

maybe it's not support 1.2.0?

**Comment by marghidanu** [comment]
I managed to bypass the markd error by doing these steps:
`
* Clone `markd` somewhere on disk
*  Added it to CRYSTAL_PATH using the following command: `export CRYSTAL_PATH=/path/to/markd/src:$(crystal env CRYSTAL_PATH)`
* Changed the markd path to `require "markd"` in these two files: `'/opt/homebrew/Cellar/crystal/1.2.1/src/compiler/crystal/tools/doc/generator.cr` and `/opt/homebrew/Cellar/crystal/1.2.1/src/compiler/crystal/tools/playground/server.cr`

Tried to rebuild but now it seems to fail with a different error:

```
Dependencies are satisfied
Building: crystalline
Error target crystalline failed to compile:
Showing last frame. Use --error-trace for full trace.

There was a problem expanding macro 'string'

Code in src/crystalline/lsp/base/code_action_kind.cr:11:1

 11 | Enum.string CodeActionKind, mappings: {
      ^
Called macro defined in src/crystalline/lsp/ext/enum.cr:3:3

 3 | macro string(name, *, downcase = true, mappings = nil, &block)

Which expanded to:

 > 27 |       end
 > 28 |
 > 29 |       def to_json(builder : JSON::Builder) : IO
                                                     ^-
Error: method CodeActionKind#to_json must return IO but it is returning Nil
```

**Comment by marghidanu** [comment]
Hmmm, is anybody maintaining the repo? Seems to be zero activity, and also no replies for some time.

**Comment by elbywan** [comment]
Hey @marghidanu,

> Hmmm, is anybody maintaining the repo? 

I am still reading issues and PRs, but sadly I do not have time these days to do much more than that, sorry 😕.

**Comment by blipmusic** [comment]
That's a real pity, but also the nature of most open source projects. Developers give up lots of spare time to deliver a product us users expect to get for free. Anyway, thanks for your work so far @elbywan! Perhaps in due time crystalline can be picked up again, or forked.

Crystal could really do with a good lsp implementation - I've been spoiled by Rust + rust-analyzer. Scry also seems stale at this point.

**Comment by travisgalloway** [comment]
Per previous responses, I was able to get a _mostly_ working build on a M1 Mac with two workarounds.

First by copying the 1.2.x lib/markd dir to the brew install dir.
```
git clone https://github.com/crystal-lang/crystal.git
cp crystal/lib /opt/homebrew/Cellar/crystal/1.2.2/lib
``

Then to avoid the enum macro error, I changed the return type of the `to_json` method. Not a permanent fix, but will complete the build. 
```
/src/crystalline/lsp/ext/enum.cr:16
-      def to_json(builder : JSON::Builder) : IO
+      def to_json(builder : JSON::Builder) : Nil
```

**Comment by blipmusic** [comment]
> First by copying the 1.2.x lib/markd dir to the brew install dir. (...)

This made compilation work for me as well (M1 Mac), thanks! But you probably need `cp -r`, right?

```
cp -r crystal/lib /opt/homebrew/Cellar/crystal/1.2.2/lib
```

**Comment by elbywan** [comment]
With the latest commits building the lib should be straightforward now, and the `markd` shenanigans should not be needed anymore.

**Comment by marghidanu** [comment]
Thank you @elbywan. Just compiled it from scratch on my M1 machine and it works fine!

**Comment by blipmusic** [comment]
Thanks, compiles fine here as well!
