### ISSUE TITLE
Incorrectly reports undefined constants

### ISSUE THREAD

**Issue by rightbrace** [elbywan/crystalline#35]
I have an entry file A, which requires B, C, and D. B and C use types from D, but they're always available since A requires them first. This all compiles fine, but crystallline is complaining about undefined constants referenced in B or C from D. What's weird is that it only starts complaining about that when I save B or C, if I save A (even without changes), its fine again. My shard.yml contains:

```yml
targets:
  shapes:
    main: src/A
```
where A is the appropriate filename.

Is this a bug, if not, is there something I can do to force crystalline to do whatever it does when I save A?

**Comment by nicklatch** [comment]
Sorry to revive and old issue, but did you ever find a solution?

**Comment by elbywan** [comment]
This should do the trick:

```cr
crystalline:
  main: src/A.cr
```
