### ISSUE TITLE
Hover provider returning "?" for any variable

### ISSUE THREAD

**Issue by jinn999** [elbywan/crystalline#4]
Hi,
first of all, gratz for the great work!

That being said, I have a problem with the hover provider, I am probably doing something wrong from my part, but I cannot really understand what.
For any variable, when I hover on it, I always get a "?" as an answer, like the following one:
![image](https://user-images.githubusercontent.com/1804165/94267610-31fce780-ff3c-11ea-8564-e8016527107a.png)
Is it something normal or is something I can fix?

**Comment by elbywan** [comment]
Hi @jinn999,

> first of all, gratz for the great work!

Thanks! ❤️ 

> For any variable, when I hover on it, I always get a "?" as an answer, like the following one:

`?` means that the semantic analysis is unable to type your variable. 

Is it located inside a function that never gets called in your code by any chance? For instance:

<img src="https://user-images.githubusercontent.com/3428394/94268209-1d6d1f00-ff3d-11ea-888c-899b180711c2.png" width="300"></img>
<img src="https://user-images.githubusercontent.com/3428394/94268220-2231d300-ff3d-11ea-8939-e3fbdf4a6acf.png" width="300"></img>

One way to work around that issue would be to write specs testing your code (or create a file calling your functions), and [use them as the entry point](https://github.com/elbywan/crystalline#entry-point) for crystalline.

**Comment by jinn999** [comment]
Thanks, that was kinda it - but I'm screwed any way :)
What was happening is that 
- I had the entry point setup correctly (requiring all specs)
- putting statements in the entry point file was correctly giving me the definitions.
- Specs still were not analyzed - hovering on variables in the specs was failing
- creating a new basic (require "spec") spec was working. 

I found out that the reason for this is that I don't use the normal builtin library for specs, but "spectator". Code written in specs goes into a macro, so that is probably the reason why I was not seeing anything :/ 

Thanks a lot for the info and again gratz!

**Comment by elbywan** [comment]
> Code written in specs goes into a macro, so that is probably the reason why I was not seeing anything 

Ah yeah I guess that's it unfortunately :/.
