### ISSUE TITLE
indentation error when enable lsp with crystallize.

### ISSUE THREAD

**Issue by zw963** [elbywan/crystalline#42]
Please check following code example:

```cr
macro included
  def hello
    puts "hello"
  end
  end
```

The end in the last line not get indent correct.

If disable lsp with `lsp-disconnect`, it works as expected.

**Comment by elbywan** [comment]
Hey @zw963,

`crystalline` uses the official formatter from the compiler. Try to run `crystal tool format` on your snippet, it should be the same.

**Comment by zw963** [comment]
Yes, you are right, the compiler just no-op, keep the wrong indentation no touch.
