### ISSUE TITLE
Wrong branch referenced in README

### ISSUE THREAD

**Issue by Tch1b0** [elbywan/crystalline#44]
In the **Scoped Install** `.shard.yml` code block, the branch `main` is referenced, even though it does not exist.

https://github.com/elbywan/crystalline/blob/a7c9aba74c43efce53941f940da0e1485e95bc7f/README.md?plain=1#L91
So instead of `main`, the value should be `master`.

**Comment by elbywan** [comment]
Absolutely, thanks for raising the issue.
