### ISSUE TITLE
Incorrect info in methods

### ISSUE THREAD

**Issue by dogweather** [elbywan/crystalline#45]
I have a file that cystalline seems to have problems with. Is there somewhere I could look in the code to help contribute?

<img width="162" alt="Screen Shot 2022-09-28 at 10 26 52 PM" src="https://user-images.githubusercontent.com/150670/192938799-4327462a-e429-422a-978c-0608f94d1a8b.png">

<img width="133" alt="Screen Shot 2022-09-28 at 10 23 53 PM" src="https://user-images.githubusercontent.com/150670/192938588-1bfffc73-e6fc-42ce-ad06-7a295acf1f47.png">

How would I test whether this is a VS Code extension vs. Crystalline issue? 

This is the code it has problems with:

```crystal
module PostProcess
  extend self

  ORS_CHAPTER_REGEX = /ORS Chapter (?<num>[1-9]\w?\w?\w?)\b/

  def add_ors_chapter_links(text : String) : String
    return text if text.blank?

    text.gsub(ORS_CHAPTER_REGEX) do |_, match|
      full_citation = match[0]
      number = match.named_captures["num"]
      chapter_url = "/statutes/ors_chapter_#{number}"

      "<a href='#{chapter_url}'>#{full_citation}</a>"
    end
  end
end

```

It has this issue in all my methods, except this one, which it handles fine. If I remove the graphql annotations, it fails. (?)

```crystal
@[GraphQL::Object]
class Query < GraphQL::BaseQuery
  @[GraphQL::Field(description: "Modify existing links when there's a pinpoint citation.")]
  def add_pinpoint_links(html : String) : String
    PinpointXref.add_pinpoint(html)
  end
end
```

**Comment by dogweather** [comment]
I'm using it compiled from `master`.

**Comment by elbywan** [comment]
Hey @dogweather,

Crystalline uses the crystal compiler under the hood which only type functions when they are called at least once in the code.

See [limitations](https://github.com/elbywan/crystalline#limitations) and https://github.com/elbywan/crystalline/issues/4.

**Comment by dogweather** [comment]
Thanks @elbywan I wonder if there's a possible workaround — a way to have a file that calls library functions, which is only loaded in development ?

**Comment by elbywan** [comment]
> I wonder if there's a possible workaround

Yes there is, you could write specs and use them as the entry point for instance.

This is highlighted in the readme [here](https://github.com/elbywan/crystalline#entry-point).
