### ISSUE TITLE
Provide musl based builds

### ISSUE THREAD

**Issue by notramo** [elbywan/crystalline#50]
Please provide musl based builds in releases, because some Linux distro can not run glibc binaries (Alpine, Void Linux musl).
A statically linked binary would work both on glibc and musl systems.

**Comment by elbywan** [comment]
Hey @notramo,

It should already be the case: https://github.com/elbywan/crystalline/blob/master/Dockerfile

**Comment by notramo** [comment]
@elbywan this is the case indeed, however, the Linux executable in the Releases page is incorrectly named *linux-gnu.gz

**Comment by elbywan** [comment]
Indeed I'll look into it, thanks for reporting the issue!
