### ISSUE TITLE
Pressing “goto definition” on `.new()` should go to `#initialize()`

### ISSUE THREAD

**Issue by notramo** [elbywan/crystalline#51]
`.new()` calls `#initialize()`, but `.new()` is not defined with `def`, and `#initialize` is never called manually.
So `.new()` is defined as `#initialize()` effectively, and “goto definition” on `.new()` should open `#initialize()`.

**Comment by elbywan** [comment]
Hey @notramo 

It seems like it's working fine on my end.

https://user-images.githubusercontent.com/3428394/201674414-8d4e4266-0518-4931-80b4-00c0d65f8415.mov
