### ISSUE TITLE
[RFC] Extract LSP protocol-only code to a separate shard

### ISSUE THREAD

**Issue by asterite** [elbywan/crystalline#54]
Extracted from #53

I think it would be nice to extract the code that's exclusive to  LSP to a separate shard. The advantages of doing that are:
1. Clearer separation of concerns
2. Less code in this repository, making it more accessible
3. Avoiding duplicating code and effort (there's already [another repo](https://github.com/jemc/crystal-lsp) for this)
4. Allowing others to use the LSP shard for other language server implementations (not only Crystal ones. For example there could be one for [Mint](https://github.com/mint-lang/mint)).

One possible place for this new repo could be in `elbywan`. Another place could be [crystal-community](https://github.com/crystal-community) to encourage contributions.

**Comment by elbywan** [comment]
> I think it would be nice to extract the code that's exclusive to LSP to a separate shard.

Yes definitely, for the time being under `elbywan` because it is easier for me. In the long run, I have no issues with it being ported over to the `crystal-community` org.

 It should be pretty quick and I can work on it in the following days + a PR to make `crystalline` use the shard.

_On a side note, extracting the LSP should not be blocking any other topics since it does not change anything to import it or use the embedded version_

**Comment by asterite** [comment]
> On a side note, extracting the LSP should not be blocking any other topics since it does not change anything internally to import it or use the embedded version

Definitely!

Another thing I was thinking is that right now types aren't defined in places where it's idiomatic to find them. For example `Crystalline::Diagnostics` is at `src/crystalline/classes/diagnostics.cr` instead of `src/crystalline/diagnostics.cr` and it takes a few seconds/minutes to realize this. So moving LSP to a shard would also allow moving things directly into `src/crystalline` (well, I guess that could be done at any time.)

**Comment by elbywan** [comment]
There we go for the extracted shard: https://github.com/elbywan/crystal-lsp

> Another thing I was thinking is that right now types aren't defined in places where it's idiomatic to find them. For example Crystalline::Diagnostics is at src/crystalline/classes/diagnostics.cr instead of src/crystalline/diagnostics.cr and it takes a few seconds/minutes to realize this. So moving LSP to a shard would also allow moving things directly into src/crystalline (well, I guess that could be done at any time.)

Sure! I will handle this in the follow up pull reuqest to plug the new shard into crystalline.

**Comment by asterite** [comment]
Thank you, this is fantastic! I really like it that you also extracted the server and the loop, so an implementor just needs to define the `on_...` methods. In my proposal I just had in mind the types that get transmitted over the protocol, not the protocol implementation, but in retrospective what you did is much better 💙

**Comment by elbywan** [comment]
> Thank you, this is fantastic! I really like it that you also extracted the server and the loop, so an implementor just needs to define the on_... methods. In my proposal I just had in mind the types that get transmitted over the protocol, not the protocol implementation, but in retrospective what you did is much better 💙

Thanks! This is the way I designed the LSP part from the start, so people can reuse the server if they don't want to reinvent the wheel 😉.

And there we go for the follow-up PR integrating the shard and cleaning up things a bit: https://github.com/elbywan/crystalline/pull/56

So I thing we should be good regarding the LSP side now!
