### ISSUE TITLE
Crystalline Fails to Run on Apple M2 Max due to Hardcoded Path and Architecture Mismatch for libyaml

### ISSUE THREAD

**Issue by CharlonTank** [elbywan/crystalline#68]
Title: **Crystalline Fails to Run on Apple M2 Max due to Hardcoded Path and Architecture Mismatch for libyaml**

Body:

Hello,

I am running into an issue where Crystalline fails to execute due to a hardcoded path and architecture mismatch for `libyaml-0.2.dylib` on my Apple M2 Max MacBook Pro.

#### Environment:

- Device: MacBook Pro 14" (M2 Max)
- OS: macOS Ventura (13.4.1)
- Architecture: Apple M2 Max (ARM64)
- Crystal version: 1.8.2
- Installation method: Downloaded the latest binary from the Crystalline GitHub releases page and installed it using the provided instructions.

#### Steps to reproduce:

1. Download and install Crystalline using the provided instructions.
2. Run `crystalline` in the terminal.
   
#### Expected Behavior:

Crystalline starts without issues.

#### Actual Behavior:

Crystalline fails to start and outputs the following error message:

```bash
dyld[9519]: Library not loaded: /opt/homebrew/Cellar/libyaml/0.2.5/lib/libyaml-0.2.dylib
Referenced from: <27D3AB98-2C98-3AA6-A598-A3E873DC8D20> /opt/homebrew/bin/crystalline
Reason: tried: '/opt/homebrew/Cellar/libyaml/0.2.5/lib/libyaml-0.2.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/libyaml/0.2.5/lib/libyaml-0.2.dylib' (no such file), '/opt/homebrew/Cellar/libyaml/0.2.5/lib/libyaml-0.2.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/local/lib/libyaml-0.2.dylib' (no such file), '/usr/lib/libyaml-0.2.dylib' (no such file, not in dyld cache)
fish: Job 1, 'crystalline' terminated by signal SIGABRT (Abort)
```

It appears that Crystalline is looking for `libyaml-0.2.dylib` at `/usr/local/opt/libyaml/lib/libyaml-0.2.dylib`, but on my system, the library is located at `/opt/homebrew/Cellar/libyaml/0.2.5/lib/libyaml-0.2.dylib`. Furthermore, there seems to be an architecture mismatch issue as the system is `arm64` but Crystalline requires `x86_64`.

Any help or guidance on this issue would be appreciated, especially in regard to getting Crystalline to run on Apple's ARM-based M series chips.

Charlon

**Comment by elbywan** [comment]
Hey @CharlonTank,

> the system is arm64 but Crystalline requires x86_64

This is the root issue, and I cannot provide `arm64` binaries to download (sorry :/) because Github only provides x64 mac machines when running Github Actions.

You will either have to build [crystalline from source](https://github.com/elbywan/crystalline#build-from-source) or if you feel like it you can try a user-provided  arm64 binary [in this thread](https://github.com/elbywan/crystalline/issues/34).

**Comment by CharlonTank** [comment]
> Hey @CharlonTank,
> 
> > the system is arm64 but Crystalline requires x86_64
> 
> This is the root issue, and I cannot provide `arm64` binaries to download (sorry :/) because Github only provides x64 mac machines when running Github Actions.
> 
> You will either have to build [crystalline from source](https://github.com/elbywan/crystalline#build-from-source) or if you feel like it you can try a user-provided arm64 binary [in this thread](https://github.com/elbywan/crystalline/issues/34).

Thank you, I did that, but now I get compilation errors that I don't understand in my first migration file, I sent the error on Lucky framework discord

**Comment by mloughran** [comment]
It might be nice to [add a homebrew formula](https://docs.brew.sh/Adding-Software-to-Homebrew), since then homebrew would take care of building an appropriate binary for each architecture.

**Comment by mloughran** [comment]
This should have been closed by #71.

**Comment by krthr** [comment]
It seems GitHub already started to offer M1 images  👀 

https://github.com/actions/runner-images/issues/8439
https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/

**Comment by DmarshalTU** [comment]
Just wanted to point out that, as a Mason user with Neovim, I'm experiencing issues because Mason directs to this repo for the package. The installation fails due to the lack of support for Apple Silicon architecture.

<img width="500" alt="image" src="https://github.com/elbywan/crystalline/assets/59089266/072b2938-9f3e-4f85-a697-bbc341148e99">

So, if a compatible package becomes available here in the future, it would be great to notify them to add it.

**Comment by kgantchev** [comment]
> It seems GitHub already started to offer M1 images 👀


You can also use the [FlyCI](https://www.flyci.net/)'s M1 and M2 runners. Our runners are on average 2x faster and 2x cheaper than GitHub's **AND** we have a free tier for OSS projects (see below).

## Install Instructrions 

Easily replace your M1 runners: 
```diff
jobs:
 ci:
-    runs-on: macos-latest
+    runs-on: flyci-macos-large-latest-m1
   steps:
   - name: 👀 Checkout repo
     uses: actions/checkout@v4
```

Or try the M2 runners: 
```diff
jobs:
  ci:
-    runs-on: macos-latest
+    runs-on: flyci-macos-large-latest-m2
    steps:
      - name: 👀 Checkout repo
        uses: actions/checkout@v4
 ```

## Pricing  

| Processor | vCPU | RAM (GB) | Storage | Label | Price on FlyCI | Price on GitHub |
|-----------|-------|-----------|----------|-------------------------------|----------------|-----------------|
| M1        | 4    | 7        | 28 GB | flyci-macos-large-latest-m1   | $0.06          | -             |
| M1        | 8    | 14       | 28 GB | flyci-macos-xlarge-latest-m1  | $0.12          | $0.16           |
| M2        | 4    | 7        | 28 GB | flyci-macos-large-latest-m2   | $0.08          | -             |
| M2        | 8    | 14       | 28 GB | flyci-macos-xlarge-latest-m2  | $0.16          | -             |

## 500 mins/month Free for Public Repos

If your repo is public, then FlyCI offers 500 mins/month of free M1 runner usage with the `flyci-macos-large-latest-m1` runner.  

Best Regards,
Kiril Gantchev
CEO and co-founder of [FlyCI](https://flyci.net)

**Comment by elbywan** [comment]
Closing because the CI now produces arm64 darwin binaries.
