### ISSUE TITLE
Linker error on ArchLinux since 0.7.0

### ISSUE THREAD

**Issue by hugopl** [elbywan/crystalline#70]
Hi,

When trying to compile crystalline on Archlinux it errors out with a linker error:

```
Dependencies are satisfied
Building: crystalline
Error target crystalline failed to compile:     
/usr/bin/ld: /tmp/cchyRA6H.ltrans0.ltrans.o:(.debug_info+0x2b): undefined reference to `llvm_ext.cc.c4a0b00d'
/usr/bin/ld: /tmp/cchyRA6H.ltrans0.ltrans.o:(.debug_info+0x34): undefined reference to `llvm_ext.cc.c4a0b00d'
/usr/bin/ld: /tmp/cchyRA6H.ltrans0.ltrans.o:(.debug_info+0x4f): undefined reference to `llvm_ext.cc.c4a0b00d'
/usr/bin/ld: /tmp/cchyRA6H.ltrans0.ltrans.o:(.debug_info+0x56): undefined reference to `llvm_ext.cc.c4a0b00d'
/usr/bin/ld: /tmp/cchyRA6H.ltrans0.ltrans.o:(.debug_info+0x5e): undefined reference to `llvm_ext.cc.c4a0b00d'
/usr/bin/ld: /tmp/cchyRA6H.ltrans0.ltrans.o:(.debug_info+0x79): more undefined references to `llvm_ext.cc.c4a0b00d' follow
collect2: error: ld returned 1 exit status
Error: execution of command failed with exit status 1: cc "${@}" -o /home/hugo/src/pet/aur/crystalline-package/src/crystalline-0.10.0/bin/crystalline  -rdynamic -L/usr/bin/../lib/crystal -lyaml  /usr/lib/crystal/llvm/ext/llvm_ext.o `"/usr/bin/llvm-config" --libs --system-libs --ldflags 2> /dev/null` -lstdc++ -lpcre2-8 -lm -lgc -lpthread -levent_pthreads -levent  -levent  -lrt -lpthread -ldl
```

Looking at the information provided by https://github.com/crystal-lang/crystal/issues/13563, these symbols are on `llvm_ext.cc` on crystal sources, so I believe they must be included in Crystalline and compiled/linked in order to have it compile on Archlinux and possible other distributions.

Tested with LLVM15

**Comment by hugopl** [comment]
llvm_ext is compiled and instaled on `/usr/lib/crystal/llvm/ext/llvm_ext.o`.

**Comment by zw963** [comment]
@hugopl , Hi, i use Arch too, compile crystalline on my laptop work well. check [this](https://github.com/elbywan/crystalline/issues/83#issuecomment-1925668228)

probably the only different with you is, i never install Crystal use package manager, instead always compile crystal compiler myself and install it into a folder, e.g. `~/Crystal/bin`, and  will copy `llvm_ext.o` into `~/Crystal/share/crystal/src/llvm/ext/llvm_ext.o`, hope can help.
