### ISSUE TITLE
Start crystalline failed partially when used with emacs.

### ISSUE THREAD

**Issue by zw963** [elbywan/crystalline#83]
Hi, not use crystalline for a long time, because it not work before, i can see notification said crystalline start successful, the process is really started too.

```sh
 ╰─ $ ps aux |grep crystalline
zw963     571897  0.3  0.3 313408 187136 ?       Ssl  04:14   0:00 /home/zw963/Crystal/bin/crystalline --stdio
```

Even, i can saw breadcrumb showed correctly, but it just not working, no any crystalline support feature available.

I saw crystalline release the new version, so just try it again. but no luck, so, i start thought, maybe this is somewhat option issue, did I enable an option that crystalline does not support?

Following is error message which enable `debug-on-error` option.

---------

<details>
<summary> error messages </summary>
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  directory-file-name(nil)
  lsp-diagnostics--update-path(nil [0 1 0 0 0])
  lsp--on-diagnostics-update-stats(#s(lsp--workspace :ewoc #s(ewoc :buffer #<buffer *lsp-log: crystalline:575670*> :pretty-printer lsp--log-entry-pp :header [[[[... #5 ... #<marker at 21732 in *lsp-log: crystalline:575670*>] #4 "" #<marker at 22227 in *lsp-log: crystalline:575670*>] #3 DL-LIST #<marker at 22227 in *lsp-log: crystalline:575670*>] [#3 [#4 [#5 ... ... #<marker at 7363 in *lsp-log: crystalline:575670*>] #s(lsp--log-entry :timestamp "04:27:12 AM" :process-time 105 :type incoming-resp :method "initialize" :id 1 :body #<hash-table equal 1/1 0x155684bb47b1>) #<marker at 6940 in *lsp-log: crystalline:575670*>] #s(lsp--log-entry :timestamp "04:27:11 AM" :process-time nil :type outgoing-req :method "initialize" :id 1 :body (:processId 575232 :rootPath "/home/zw963/Crystal/crystal-china/translater" :clientInfo ... :rootUri "file:///home/zw963/Crystal/crystal-china/tra..." :capabilities ... :initializationOptions nil :workDoneToken "1")) #<marker at 1 in *lsp-log: crystalline:575670*>] "" #<marker at 1 in *lsp-log: crystalline:575670*>] :footer [[[[... #5 ... #<marker at 21311 in *lsp-log: crystalline:575670*>] #4 #s(lsp--log-entry :timestamp "04:27:12 AM" :process-time nil :type incoming-notif :method "$/progress" :id nil :body #<hash-table equal 2/2 0x155682caf0e9>) #<marker at 21480 in *lsp-log: crystalline:575670*>] #3 #s(lsp--log-entry :timestamp "04:27:12 AM" :process-time nil :type incoming-notif :method "textDocument/publishDiagnostics" :id nil :body #<hash-table equal 2/2 0x155684e168a5>) #<marker at 21732 in *lsp-log: crystalline:575670*>] [#3 [#4 [#5 ... ... #<marker at 1 in *lsp-log: crystalline:575670*>] "" #<marker at 1 in *lsp-log: crystalline:575670*>] DL-LIST #<marker at 22227 in *lsp-log: crystalline:575670*>] "" #<marker at 22227 in *lsp-log: crystalline:575670*>] :dll [[[[... #5 ... #<marker at 21480 in *lsp-log: crystalline:575670*>] #4 #s(lsp--log-entry :timestamp "04:27:12 AM" :process-time nil :type incoming-notif :method "textDocument/publishDiagnostics" :id nil :body #<hash-table equal 2/2 0x155684e168a5>) #<marker at 21732 in *lsp-log: crystalline:575670*>] #3 "" #<marker at 22227 in *lsp-log: crystalline:575670*>] [#3 [#4 [#5 ... ... #<marker at 6940 in *lsp-log: crystalline:575670*>] #s(lsp--log-entry :timestamp "04:27:11 AM" :process-time nil :type outgoing-req :method "initialize" :id 1 :body ...) #<marker at 1 in *lsp-log: crystalline:575670*>] "" #<marker at 1 in *lsp-log: crystalline:575670*>] DL-LIST #<marker at 22227 in *lsp-log: crystalline:575670*>] :last-node nil :hf-pp insert) :server-capabilities #<hash-table equal 7/7 0x155684bb47d7> :registered-server-capabilities nil :root "/home/zw963/Crystal/crystal-china/translater" :client #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name environment-fn workspace) #<bytecode 0x14b5ccadbef6a0b2>) :test? #f(compiled-function () #<bytecode 0x107029217d6d02ca>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x155683a8c349> :request-handlers #<hash-table equal 0/65 0x155683a8c8f9> :response-handlers #<hash-table eql 0/65 0x155683a8cb27> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x155683a8cebb> :action-handlers #<hash-table equal 0/65 0x155683a8cedb> :major-modes (crystal-mode) :activation-fn nil :priority 0 :server-id crystalline :multi-root nil :initialization-options nil :semantic-tokens-faces-overrides nil :custom-capabilities nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn nil :remote? nil :completion-in-comments? nil :path->uri-fn nil :uri->path-fn nil :environment-fn nil :after-open-fn nil :async-request-handlers #<hash-table equal 0/65 0x155683a8d32d> :download-server-fn nil :download-in-progress? nil :buffers nil :synchronize-sections nil) :host-root nil :proc #<process crystalline> :cmd-proc #<process crystalline> :buffers (#<buffer translater.cr>) :semantic-tokens-faces nil :semantic-tokens-modifier-faces nil :extra-client-capabilities nil :status initialized :metadata #<hash-table equal 0/65 0x15568497ee67> :watches #<hash-table equal 0/65 0x15568497f13d> :workspace-folders nil :last-id 0 :status-string nil :shutdown-action nil :diagnostics #<hash-table equal 0/65 0x15568497f43b> :work-done-tokens #<hash-table equal 1/65 0x15568497f739>) #<hash-table equal 2/2 0x155684e168a5>)
  lsp--on-diagnostics(#s(lsp--workspace :ewoc #s(ewoc :buffer #<buffer *lsp-log: crystalline:575670*> :pretty-printer lsp--log-entry-pp :header [[[[... #5 ... #<marker at 21732 in *lsp-log: crystalline:575670*>] #4 "" #<marker at 22227 in *lsp-log: crystalline:575670*>] #3 DL-LIST #<marker at 22227 in *lsp-log: crystalline:575670*>] [#3 [#4 [#5 ... ... #<marker at 7363 in *lsp-log: crystalline:575670*>] #s(lsp--log-entry :timestamp "04:27:12 AM" :process-time 105 :type incoming-resp :method "initialize" :id 1 :body #<hash-table equal 1/1 0x155684bb47b1>) #<marker at 6940 in *lsp-log: crystalline:575670*>] #s(lsp--log-entry :timestamp "04:27:11 AM" :process-time nil :type outgoing-req :method "initialize" :id 1 :body (:processId 575232 :rootPath "/home/zw963/Crystal/crystal-china/translater" :clientInfo ... :rootUri "file:///home/zw963/Crystal/crystal-china/tra..." :capabilities ... :initializationOptions nil :workDoneToken "1")) #<marker at 1 in *lsp-log: crystalline:575670*>] "" #<marker at 1 in *lsp-log: crystalline:575670*>] :footer [[[[... #5 ... #<marker at 21311 in *lsp-log: crystalline:575670*>] #4 #s(lsp--log-entry :timestamp "04:27:12 AM" :process-time nil :type incoming-notif :method "$/progress" :id nil :body #<hash-table equal 2/2 0x155682caf0e9>) #<marker at 21480 in *lsp-log: crystalline:575670*>] #3 #s(lsp--log-entry :timestamp "04:27:12 AM" :process-time nil :type incoming-notif :method "textDocument/publishDiagnostics" :id nil :body #<hash-table equal 2/2 0x155684e168a5>) #<marker at 21732 in *lsp-log: crystalline:575670*>] [#3 [#4 [#5 ... ... #<marker at 1 in *lsp-log: crystalline:575670*>] "" #<marker at 1 in *lsp-log: crystalline:575670*>] DL-LIST #<marker at 22227 in *lsp-log: crystalline:575670*>] "" #<marker at 22227 in *lsp-log: crystalline:575670*>] :dll [[[[... #5 ... #<marker at 21480 in *lsp-log: crystalline:575670*>] #4 #s(lsp--log-entry :timestamp "04:27:12 AM" :process-time nil :type incoming-notif :method "textDocument/publishDiagnostics" :id nil :body #<hash-table equal 2/2 0x155684e168a5>) #<marker at 21732 in *lsp-log: crystalline:575670*>] #3 "" #<marker at 22227 in *lsp-log: crystalline:575670*>] [#3 [#4 [#5 ... ... #<marker at 6940 in *lsp-log: crystalline:575670*>] #s(lsp--log-entry :timestamp "04:27:11 AM" :process-time nil :type outgoing-req :method "initialize" :id 1 :body ...) #<marker at 1 in *lsp-log: crystalline:575670*>] "" #<marker at 1 in *lsp-log: crystalline:575670*>] DL-LIST #<marker at 22227 in *lsp-log: crystalline:575670*>] :last-node nil :hf-pp insert) :server-capabilities #<hash-table equal 7/7 0x155684bb47d7> :registered-server-capabilities nil :root "/home/zw963/Crystal/crystal-china/translater" :client #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name environment-fn workspace) #<bytecode 0x14b5ccadbef6a0b2>) :test? #f(compiled-function () #<bytecode 0x107029217d6d02ca>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x155683a8c349> :request-handlers #<hash-table equal 0/65 0x155683a8c8f9> :response-handlers #<hash-table eql 0/65 0x155683a8cb27> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x155683a8cebb> :action-handlers #<hash-table equal 0/65 0x155683a8cedb> :major-modes (crystal-mode) :activation-fn nil :priority 0 :server-id crystalline :multi-root nil :initialization-options nil :semantic-tokens-faces-overrides nil :custom-capabilities nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn nil :remote? nil :completion-in-comments? nil :path->uri-fn nil :uri->path-fn nil :environment-fn nil :after-open-fn nil :async-request-handlers #<hash-table equal 0/65 0x155683a8d32d> :download-server-fn nil :download-in-progress? nil :buffers nil :synchronize-sections nil) :host-root nil :proc #<process crystalline> :cmd-proc #<process crystalline> :buffers (#<buffer translater.cr>) :semantic-tokens-faces nil :semantic-tokens-modifier-faces nil :extra-client-capabilities nil :status initialized :metadata #<hash-table equal 0/65 0x15568497ee67> :watches #<hash-table equal 0/65 0x15568497f13d> :workspace-folders nil :last-id 0 :status-string nil :shutdown-action nil :diagnostics #<hash-table equal 0/65 0x15568497f43b> :work-done-tokens #<hash-table equal 1/65 0x15568497f739>) #<hash-table equal 2/2 0x155684e168a5>)
  lsp--on-notification(#s(lsp--workspace :ewoc #s(ewoc :buffer #<buffer *lsp-log: crystalline:575670*> :pretty-printer lsp--log-entry-pp :header [[[[... #5 ... #<marker at 21732 in *lsp-log: crystalline:575670*>] #4 "" #<marker at 22227 in *lsp-log: crystalline:575670*>] #3 DL-LIST #<marker at 22227 in *lsp-log: crystalline:575670*>] [#3 [#4 [#5 ... ... #<marker at 7363 in *lsp-log: crystalline:575670*>] #s(lsp--log-entry :timestamp "04:27:12 AM" :process-time 105 :type incoming-resp :method "initialize" :id 1 :body #<hash-table equal 1/1 0x155684bb47b1>) #<marker at 6940 in *lsp-log: crystalline:575670*>] #s(lsp--log-entry :timestamp "04:27:11 AM" :process-time nil :type outgoing-req :method "initialize" :id 1 :body (:processId 575232 :rootPath "/home/zw963/Crystal/crystal-china/translater" :clientInfo ... :rootUri "file:///home/zw963/Crystal/crystal-china/tra..." :capabilities ... :initializationOptions nil :workDoneToken "1")) #<marker at 1 in *lsp-log: crystalline:575670*>] "" #<marker at 1 in *lsp-log: crystalline:575670*>] :footer [[[[... #5 ... #<marker at 21311 in *lsp-log: crystalline:575670*>] #4 #s(lsp--log-entry :timestamp "04:27:12 AM" :process-time nil :type incoming-notif :method "$/progress" :id nil :body #<hash-table equal 2/2 0x155682caf0e9>) #<marker at 21480 in *lsp-log: crystalline:575670*>] #3 #s(lsp--log-entry :timestamp "04:27:12 AM" :process-time nil :type incoming-notif :method "textDocument/publishDiagnostics" :id nil :body #<hash-table equal 2/2 0x155684e168a5>) #<marker at 21732 in *lsp-log: crystalline:575670*>] [#3 [#4 [#5 ... ... #<marker at 1 in *lsp-log: crystalline:575670*>] "" #<marker at 1 in *lsp-log: crystalline:575670*>] DL-LIST #<marker at 22227 in *lsp-log: crystalline:575670*>] "" #<marker at 22227 in *lsp-log: crystalline:575670*>] :dll [[[[... #5 ... #<marker at 21480 in *lsp-log: crystalline:575670*>] #4 #s(lsp--log-entry :timestamp "04:27:12 AM" :process-time nil :type incoming-notif :method "textDocument/publishDiagnostics" :id nil :body #<hash-table equal 2/2 0x155684e168a5>) #<marker at 21732 in *lsp-log: crystalline:575670*>] #3 "" #<marker at 22227 in *lsp-log: crystalline:575670*>] [#3 [#4 [#5 ... ... #<marker at 6940 in *lsp-log: crystalline:575670*>] #s(lsp--log-entry :timestamp "04:27:11 AM" :process-time nil :type outgoing-req :method "initialize" :id 1 :body ...) #<marker at 1 in *lsp-log: crystalline:575670*>] "" #<marker at 1 in *lsp-log: crystalline:575670*>] DL-LIST #<marker at 22227 in *lsp-log: crystalline:575670*>] :last-node nil :hf-pp insert) :server-capabilities #<hash-table equal 7/7 0x155684bb47d7> :registered-server-capabilities nil :root "/home/zw963/Crystal/crystal-china/translater" :client #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name environment-fn workspace) #<bytecode 0x14b5ccadbef6a0b2>) :test? #f(compiled-function () #<bytecode 0x107029217d6d02ca>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x155683a8c349> :request-handlers #<hash-table equal 0/65 0x155683a8c8f9> :response-handlers #<hash-table eql 0/65 0x155683a8cb27> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x155683a8cebb> :action-handlers #<hash-table equal 0/65 0x155683a8cedb> :major-modes (crystal-mode) :activation-fn nil :priority 0 :server-id crystalline :multi-root nil :initialization-options nil :semantic-tokens-faces-overrides nil :custom-capabilities nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn nil :remote? nil :completion-in-comments? nil :path->uri-fn nil :uri->path-fn nil :environment-fn nil :after-open-fn nil :async-request-handlers #<hash-table equal 0/65 0x155683a8d32d> :download-server-fn nil :download-in-progress? nil :buffers nil :synchronize-sections nil) :host-root nil :proc #<process crystalline> :cmd-proc #<process crystalline> :buffers (#<buffer translater.cr>) :semantic-tokens-faces nil :semantic-tokens-modifier-faces nil :extra-client-capabilities nil :status initialized :metadata #<hash-table equal 0/65 0x15568497ee67> :watches #<hash-table equal 0/65 0x15568497f13d> :workspace-folders nil :last-id 0 :status-string nil :shutdown-action nil :diagnostics #<hash-table equal 0/65 0x15568497f43b> :work-done-tokens #<hash-table equal 1/65 0x15568497f739>) #<hash-table equal 3/3 0x155684e1685f>)
  lsp--parser-on-message(#<hash-table equal 3/3 0x155684e1685f> #s(lsp--workspace :ewoc #s(ewoc :buffer #<buffer *lsp-log: crystalline:575670*> :pretty-printer lsp--log-entry-pp :header [[[[... #6 ... #<marker at 21732 in *lsp-log: crystalline:575670*>] #5 "" #<marker at 22227 in *lsp-log: crystalline:575670*>] #4 DL-LIST #<marker at 22227 in *lsp-log: crystalline:575670*>] [#4 [#5 [#6 ... ... #<marker at 7363 in *lsp-log: crystalline:575670*>] #s(lsp--log-entry :timestamp "04:27:12 AM" :process-time 105 :type incoming-resp :method "initialize" :id 1 :body #<hash-table equal 1/1 0x155684bb47b1>) #<marker at 6940 in *lsp-log: crystalline:575670*>] #s(lsp--log-entry :timestamp "04:27:11 AM" :process-time nil :type outgoing-req :method "initialize" :id 1 :body (:processId 575232 :rootPath "/home/zw963/Crystal/crystal-china/translater" :clientInfo ... :rootUri "file:///home/zw963/Crystal/crystal-china/tra..." :capabilities ... :initializationOptions nil :workDoneToken "1")) #<marker at 1 in *lsp-log: crystalline:575670*>] "" #<marker at 1 in *lsp-log: crystalline:575670*>] :footer [[[[... #6 ... #<marker at 21311 in *lsp-log: crystalline:575670*>] #5 #s(lsp--log-entry :timestamp "04:27:12 AM" :process-time nil :type incoming-notif :method "$/progress" :id nil :body #<hash-table equal 2/2 0x155682caf0e9>) #<marker at 21480 in *lsp-log: crystalline:575670*>] #4 #s(lsp--log-entry :timestamp "04:27:12 AM" :process-time nil :type incoming-notif :method "textDocument/publishDiagnostics" :id nil :body #<hash-table equal 2/2 0x155684e168a5>) #<marker at 21732 in *lsp-log: crystalline:575670*>] [#4 [#5 [#6 ... ... #<marker at 1 in *lsp-log: crystalline:575670*>] "" #<marker at 1 in *lsp-log: crystalline:575670*>] DL-LIST #<marker at 22227 in *lsp-log: crystalline:575670*>] "" #<marker at 22227 in *lsp-log: crystalline:575670*>] :dll [[[[... #6 ... #<marker at 21480 in *lsp-log: crystalline:575670*>] #5 #s(lsp--log-entry :timestamp "04:27:12 AM" :process-time nil :type incoming-notif :method "textDocument/publishDiagnostics" :id nil :body #<hash-table equal 2/2 0x155684e168a5>) #<marker at 21732 in *lsp-log: crystalline:575670*>] #4 "" #<marker at 22227 in *lsp-log: crystalline:575670*>] [#4 [#5 [#6 ... ... #<marker at 6940 in *lsp-log: crystalline:575670*>] #s(lsp--log-entry :timestamp "04:27:11 AM" :process-time nil :type outgoing-req :method "initialize" :id 1 :body ...) #<marker at 1 in *lsp-log: crystalline:575670*>] "" #<marker at 1 in *lsp-log: crystalline:575670*>] DL-LIST #<marker at 22227 in *lsp-log: crystalline:575670*>] :last-node nil :hf-pp insert) :server-capabilities #<hash-table equal 7/7 0x155684bb47d7> :registered-server-capabilities nil :root "/home/zw963/Crystal/crystal-china/translater" :client #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name environment-fn workspace) #<bytecode 0x14b5ccadbef6a0b2>) :test? #f(compiled-function () #<bytecode 0x107029217d6d02ca>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x155683a8c349> :request-handlers #<hash-table equal 0/65 0x155683a8c8f9> :response-handlers #<hash-table eql 0/65 0x155683a8cb27> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x155683a8cebb> :action-handlers #<hash-table equal 0/65 0x155683a8cedb> :major-modes (crystal-mode) :activation-fn nil :priority 0 :server-id crystalline :multi-root nil :initialization-options nil :semantic-tokens-faces-overrides nil :custom-capabilities nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn nil :remote? nil :completion-in-comments? nil :path->uri-fn nil :uri->path-fn nil :environment-fn nil :after-open-fn nil :async-request-handlers #<hash-table equal 0/65 0x155683a8d32d> :download-server-fn nil :download-in-progress? nil :buffers nil :synchronize-sections nil) :host-root nil :proc #<process crystalline> :cmd-proc #<process crystalline> :buffers (#<buffer translater.cr>) :semantic-tokens-faces nil :semantic-tokens-modifier-faces nil :extra-client-capabilities nil :status initialized :metadata #<hash-table equal 0/65 0x15568497ee67> :watches #<hash-table equal 0/65 0x15568497f13d> :workspace-folders nil :last-id 0 :status-string nil :shutdown-action nil :diagnostics #<hash-table equal 0/65 0x15568497f43b> :work-done-tokens #<hash-table equal 1/65 0x15568497f739>))
  #f(compiled-function (msg) #<bytecode -0x805d0505285bf3b>)(#<hash-table equal 3/3 0x155684e1685f>)
  mapc(#f(compiled-function (msg) #<bytecode -0x805d0505285bf3b>) (#<hash-table equal 3/3 0x155684e1685f> #<hash-table equal 3/3 0x155684e573bf>))
  #f(compiled-function (proc input) #<bytecode -0x1344e64239e1ad6b>)(#<process crystalline> "Content-Length: 320\15\n\15\n{\"jsonrpc\":\"2.0\",\"method\":\"textDocument/publishDiagnostics\",\"params\":{\"uri\":\"file://\",\"diagnostics\":[{\"range\":{\"start\":{\"line\":0,\"character\":-1},\"end\":{\"line\":0,\"character\":-1}},\"severity\":1,\"source\":\"\",\"message\":\"abstract `def Object#hash(hasher)` must be implemented by ReferenceStorage(T)\",\"relatedInformation\":[]}]}}Content-Length: 138\15\n\15\n{\"jsonrpc\":\"2.0\",\"method\":\"$/progress\",\"params\":{\"token\":\"workspace/compile/0\",\"value\":{\"message\":\"Completed with errors.\",\"kind\":\"end\"}}}")
</details>

-----------------

It look's like those error about lsp update `diagnostics` status? but, i checked the README, it said, crystalline support diagnostics, right?

BTW: there should not a emacs config issue, at least, the emacs lsp for go, rust use same settings, work quite well.

My emacs lsp settings is [here](https://github.com/zw963/.emacs.d/blob/master/plugins/lsp-mode/lsp-mode_init.el)

thanks.

**Comment by elbywan** [comment]
Hey @zw963,

> It look's like those error about lsp update diagnostics status? 

I can see this error in the logs: `def Object#hash(hasher) must be implemented by ReferenceStorage(T)`

It seems related to the following crystal bug: https://github.com/crystal-lang/crystal/issues/14194. Since crystalline uses `v1.11.0` to compile your program, maybe you are using an older crystal version?

> crystalline support diagnostics, right?

Yes, when crystalline is setup correctly. This is how it looks like on my end with vscode:


https://github.com/elbywan/crystalline/assets/3428394/ab16f67a-bec1-4cab-97d7-d45f64ff5c35

**Comment by zw963** [comment]
> Yes, when crystalline is setup correctly. This is how it looks like on my end with vscode:

Wow,really awesome show case!

> It seems related to the following crystal bug: https://github.com/crystal-lang/crystal/issues/14194. Since crystalline uses v1.11.0 to compile your program, maybe you are using an older crystal version?

In fact, i use Crystal 1.1.2, and always compile the Crystal compiler myself. 

```
 ╰─ $ crystal --version
Crystal 1.11.2 [fda656c71] (2024-01-18)

LLVM: 16.0.6
Default target: x86_64-pc-linux-gnu
```

but, i download crystalline from release page, because compile is slow, let me try compile it from source, and will report here.

**Comment by zw963** [comment]
Done, it spent six minutes for build a dynamic version crystalline.

```
 ╰─ $ ldd crystalline
        linux-vdso.so.1 (0x00007ffeb00ce000)
        libyaml-0.so.2 => /usr/lib/libyaml-0.so.2 (0x00007ffb7efbe000)
        libLLVM-16.so => /usr/lib/libLLVM-16.so (0x00007ffb76000000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007ffb75c00000)
        libpcre2-8.so.0 => /usr/lib/libpcre2-8.so.0 (0x00007ffb7ef23000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007ffb75f13000)
        libgc.so.1 => /usr/lib/libgc.so.1 (0x00007ffb75ea7000)
        libevent_pthreads-2.1.so.7 => /usr/lib/libevent_pthreads-2.1.so.7 (0x00007ffb7ef1c000)
        libevent-2.1.so.7 => /usr/lib/libevent-2.1.so.7 (0x00007ffb75bae000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007ffb75e82000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007ffb759cc000)
        /lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007ffb7f00a000)
        libffi.so.8 => /usr/lib/libffi.so.8 (0x00007ffb7ef11000)
        libedit.so.0 => /usr/lib/libedit.so.0 (0x00007ffb75990000)
        libz.so.1 => /usr/lib/libz.so.1 (0x00007ffb7e3e6000)
        libzstd.so.1 => /usr/lib/libzstd.so.1 (0x00007ffb758bd000)
        libncursesw.so.6 => /usr/lib/libncursesw.so.6 (0x00007ffb75846000)
        libxml2.so.2 => /usr/lib/libxml2.so.2 (0x00007ffb756dc000)
        libevent_core-2.1.so.7 => /usr/lib/libevent_core-2.1.so.7 (0x00007ffb756aa000)
        liblzma.so.5 => /usr/lib/liblzma.so.5 (0x00007ffb75677000)
        libicuuc.so.74 => /usr/lib/libicuuc.so.74 (0x00007ffb75400000)
        libicudata.so.74 => /usr/lib/libicudata.so.74 (0x00007ffb73600000)

 ╰─ $ file crystalline
crystalline: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=0c82e60e9a5a023dab725a87d24cf2deec32e873, for GNU/Linux 4.4.0, not stripped
```

It works for me now! 

I double confirm to switch back to use the github release version, still get same error.

So, any idea? 

![image](https://github.com/elbywan/crystalline/assets/549126/b7bc7bcd-5390-4701-b0f3-3be4f9fbbfd0)

**Comment by elbywan** [comment]
> It works for me now!

Great 😄 

> I double confirm to switch back to use the github release version, still get same error.

I suppose it's because the linux release binary is built with `v1.10.0`, I'll bump the crystal version o nthe CI and publish a new version.

**Comment by elbywan** [comment]
@zw963 Can you try with [this binary](https://github.com/elbywan/crystalline/actions/runs/7773207689/artifacts/1218291785) from [the latest build](https://github.com/elbywan/crystalline/actions/runs/7773207689)?

**Comment by zw963** [comment]
> @zw963 Can you try with [this binary](https://github.com/elbywan/crystalline/actions/runs/7773207689/artifacts/1218291785) from [the latest build](https://github.com/elbywan/crystalline/actions/runs/7773207689)?

It works!
