### ISSUE TITLE
Release artifact v0.13.0/crystalline_x86_64-apple-darwin.gz - Labelled wrong architecture

### ISSUE THREAD

**Issue by tuxaanand** [elbywan/crystalline#87]
Hi,

The release artifact https://github.com/elbywan/crystalline/releases/download/v0.13.0/crystalline_x86_64-apple-darwin.gz, labelled for use with MacOS on Intel x86_64 platform throws an error message that the executable is not recognizable.

Thanks,
Aanand

**Comment by elbywan** [comment]
Hey @tuxaanand,

Thanks for reporting! I just released v0.13.1 which should have the right arch, hopefully 🤞.
